import { useMemo, useState } from 'react'

/**
 * UI 状态矩阵 —— L17-06 用。
 *
 * AI 默认只生成 happy path 界面。这个组件把"一个界面到底有多少种状态"摊开，
 * 让学习者亲眼看到：把 5 个组件 × 8 种状态列成矩阵后，
 * 一句"帮我做个用户列表"背后其实藏着 40 个需要交代的分支。
 */

type StateKey =
  | 'ideal'
  | 'empty'
  | 'loading'
  | 'partial'
  | 'error'
  | 'overflow'
  | 'offline'
  | 'noMouse'

interface StateSpec {
  key: StateKey
  name: string
  /** AI 默认会不会主动生成 */
  autoGenerated: boolean
  /** 这个状态没做会怎样 */
  cost: string
  /** 该写进 Prompt 的一句约束 */
  ask: string
}

const STATES: StateSpec[] = [
  {
    key: 'ideal',
    name: '理想态',
    autoGenerated: true,
    cost: '——（这是 AI 唯一默认会做的）',
    ask: '数据齐全、数量适中时的默认呈现',
  },
  {
    key: 'empty',
    name: '空态',
    autoGenerated: false,
    cost: '新用户第一次打开就看到一片空白，以为坏了',
    ask: '零数据时展示引导文案与"创建第一条"的入口，不要只留空白',
  },
  {
    key: 'loading',
    name: '加载态',
    autoGenerated: true,
    cost: '慢网络下界面像卡死，用户反复点击造成重复提交',
    ask: '请求期间展示骨架屏，并禁用会重复提交的按钮',
  },
  {
    key: 'partial',
    name: '部分加载',
    autoGenerated: false,
    cost: '一个子请求失败导致整页白屏',
    ask: '各区块独立降级，单区块失败不影响其他区块渲染',
  },
  {
    key: 'error',
    name: '错误态',
    autoGenerated: false,
    cost: '只弹一句"出错了"，用户不知道下一步该干嘛',
    ask: '错误提示必须包含：发生了什么、用户能做什么、重试入口',
  },
  {
    key: 'overflow',
    name: '超长/超量',
    autoGenerated: false,
    cost: '一个 200 字的标题把整个布局撑破',
    ask: '文本截断策略 + 长列表虚拟化 + 最大高度约束',
  },
  {
    key: 'offline',
    name: '离线/超时',
    autoGenerated: false,
    cost: '断网时无限转圈，永远不给结论',
    ask: '设置请求超时，超时后给出离线提示与手动重试',
  },
  {
    key: 'noMouse',
    name: '键盘/读屏',
    autoGenerated: false,
    cost: '只能用鼠标操作，无障碍与效率用户全被挡在门外',
    ask: '所有交互元素可 Tab 聚焦，焦点可见，按钮有 aria-label',
  },
]

const COMPONENTS = ['列表页', '详情页', '表单', '搜索框', '设置面板']

export function UIStateMatrix() {
  const autoKeys = useMemo(
    () => STATES.filter((s) => s.autoGenerated).map((s) => s.key),
    [],
  )
  const defaultCovered = () =>
    new Set(COMPONENTS.flatMap((c) => autoKeys.map((k) => `${c}|${k}`)))

  const [covered, setCovered] = useState<Set<string>>(defaultCovered)
  const [focus, setFocus] = useState<StateKey>('empty')

  const total = COMPONENTS.length * STATES.length
  const done = covered.size
  const spec = STATES.find((s) => s.key === focus)!

  const autoCount = useMemo(
    () => COMPONENTS.length * autoKeys.length,
    [autoKeys],
  )

  function toggle(comp: string, st: StateKey) {
    const key = `${comp}|${st}`
    setCovered((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  function fillAll() {
    setCovered(
      new Set(COMPONENTS.flatMap((c) => STATES.map((s) => `${c}|${s.key}`))),
    )
  }

  function reset() {
    setCovered(defaultCovered())
  }

  return (
    <div className="card p-5">
      <h4 className="mb-3 text-sm font-semibold text-ink-100">UI 状态矩阵</h4>
      <p className="mb-4 text-xs leading-relaxed text-ink-400">
        点格子表示"这个状态我交代过了"。默认勾了理想态和加载态 —— 那正是 AI
        不加约束时偶尔会覆盖到的范围。
      </p>

      <div className="mb-4 overflow-x-auto">
        <table className="w-full min-w-[520px] border-collapse text-xs">
          <thead>
            <tr>
              <th className="p-1 text-left font-medium text-ink-400">组件 \ 状态</th>
              {STATES.map((s) => (
                <th
                  key={s.key}
                  className={`cursor-pointer p-1 text-center font-medium interactive-focus ${
                    focus === s.key ? 'text-ink-100' : 'text-ink-400'
                  }`}
                  onClick={() => setFocus(s.key)}
                  tabIndex={0}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      setFocus(s.key)
                    }
                  }}
                >
                  {s.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {COMPONENTS.map((c) => (
              <tr key={c}>
                <td className="p-1 text-ink-300">{c}</td>
                {STATES.map((s) => {
                  const on = covered.has(`${c}|${s.key}`)
                  return (
                    <td key={s.key} className="p-1 text-center">
                      <button
                        onClick={() => toggle(c, s.key)}
                        aria-label={`${c} 的${s.name}`}
                        aria-pressed={on}
                        className={`h-6 w-full rounded border transition-colors interactive-focus ${
                          on
                            ? 'border-emerald-500/60 bg-emerald-500/25 text-emerald-300'
                            : 'border-ink-700 bg-ink-800/40 text-ink-600 hover:bg-ink-700/40'
                        }`}
                      >
                        {on ? '✓' : ''}
                      </button>
                    </td>
                  )
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mb-4 flex flex-wrap items-center gap-3 text-xs">
        <span className="text-ink-300">
          已覆盖 <span className="font-semibold text-brand-300">{done}</span> / {total}
        </span>
        <span className="text-ink-500">
          AI 默认只给你 {autoCount} 格
        </span>
        <button
          onClick={fillAll}
          className="interactive-chip interactive-focus rounded px-2 py-1 text-xs"
        >
          全部勾上
        </button>
        <button
          onClick={reset}
          className="interactive-chip interactive-focus rounded px-2 py-1 text-xs"
        >
          回到默认
        </button>
      </div>

      <div className="rounded-lg border border-ink-700 bg-ink-800/40 p-3 text-xs leading-relaxed">
        <div className="mb-1 font-semibold text-ink-100">
          {spec.name}
          {!spec.autoGenerated && (
            <span className="ml-2 rounded bg-amber-500/20 px-1.5 py-0.5 text-[10px] text-amber-300">
              不写就没有
            </span>
          )}
        </div>
        <div className="text-ink-400">漏掉的代价：{spec.cost}</div>
        <div className="mt-1 text-ink-300">写进 Prompt：{spec.ask}</div>
      </div>

      <p className="mt-3 text-xs leading-relaxed text-ink-500">
        这张表的用法不是"全部填满"，而是<strong className="text-ink-300">逐格做决定</strong>：
        每一格要么实现，要么明确写下"本版不做，因为……"。
        真正危险的不是没做，是没意识到有这一格。
      </p>
    </div>
  )
}
